export const SEARCH_MOVIE = 'SEARCH_MOVIE';
export const FETCH_MOVIE = 'FETCH_MOVIE';
export const FETCH_MOVIE_ID = 'FETCH_MOVIE_ID';
export const LOADING = 'LOADING';
export const FETCH_TRENDING_MOVIES = 'FETCH_TRENDING_MOVIES';
export const SEARCH_ERROR = 'SEARCH_ERROR';